apiVersion: v1
kind: Service
metadata:
  labels:
    app: blockbuster-authentication-service
  name: blockbuster-authentication-service
spec:
  ports:
  - port: 12000
    protocol: TCP
    targetPort: 12000
  selector:
    app: blockbuster-authentication-service
  type: NodePort
status:
  loadBalancer: {}
