pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
		dir('authenticationService'){
                	sh 'mvn clean compile'
		}
            }
        }

        stage('Test') {
            steps {
		dir('authenticationService'){
                	sh 'mvn test'
		}
            }
        }
    }

    post {
        always {
		dir('authenticationService'){
            		junit '/target/surefire-reports/*.xml'
        	}
	}
    }
}