pipeline {
    agent any

    tools {
	jdk 'JDK21'
	maven 'MavenJenkins'
    }

    stages {
        stage('Build') {
            steps {
		dir('authenticationService'){
                	sh 'mvn clean compile'
		}
            }
        }

        stage('Test') {
            steps {
		dir('authenticationService'){
                	sh 'mvn test'
		}
            }
        }
    }

    post {
        always {
            	junit allowEmptyResults: true,testResults: 'authenticationService/target/surefire-reports/*.xml'
	}
    }
}